### ISSUE TITLE
search -g not return anything?

### ISSUE THREAD

**Issue by fliar** [trixnz/rustsym#2]
> rustsym search -g . main

returns

> []

while

> rustsym search -l src/main.rs main

returns

> [{"path":"src/main.rs","name":"main","container":"","kind":"function","line":8}]

**Comment by trixnz** [comment]
Hmm, it might be erroring on one of the files in the src directory. What is the directory structure of `.`? Are there any more files other than `main.rs`?

**Comment by fliar** [comment]
for your information:

> $ rustsym search . main -g
> []
> $ ls
> Cargo.lock  Cargo.toml  src  target
> $ ls src/
> main.rs

**Comment by trixnz** [comment]
Strange, its working fine here with that same structure. What OS are you running?

**Comment by fliar** [comment]
fyi, rustsym is installed by 'cargo install rustsym' btw:

> Distributor ID: Debian
> Description:    Debian GNU/Linux 8.5 (jessie)
> Release:        8.5
> Codename:       jessie

**Comment by trixnz** [comment]
Can confirm this is happening on Linux. Seems to be a sporadic failure.. sometimes I'm getting a panic. I'll get this fixed and deploy a new version.
