### ISSUE TITLE
Emit information for all modules

### ISSUE THREAD

**Issue by nox** [trixnz/rustsym#4]
Should `mod foo;` emit information for the `foo` symbol even if we don't recurse in its children in local mode?

**Comment by trixnz** [comment]
I would be hesitant to add `foo`'s symbols to the local results as I imagine it could become extremely verbose on larger projects and would detract from the value of local symbols.

**Comment by nox** [comment]
Fair enough.

**Comment by nox** [comment]
Note that it does in global mode with my patch now, though; and that inline modules now always get a symbol too.
